### ISSUE TITLE
example doesn't work...

### ISSUE THREAD

**Issue by jasonrberk** [contiamo/react-runtime-config#16]
I might be doing something else wrong, but when I follow your example, it fails to compile:

`
TypeError: getConfig is not a function
`

I had to do it like this:

`
const MyComponent = () => <Config>{getConfig => <h1 style={{ color: getConfig.getConfig("color") }}>My title</h1>}</Config>;
`

notice: getConfig.getConfig("color")

**Comment by jasonrberk** [comment]
import React, { Component } from 'react';

import Config from "./components/config/Config";

class App extends Component {
  render() {
    // fails to compile
    // const MyComponent = () => <Config>{getConfig => <h1 style={{ color: getConfig("color") }}>My title</h1>}</Config>;

    // works
    const MyComponent = () => <Config>{c => <h1 style={{ color: c.getConfig("color") }}>My title</h1>}</Config>;

    return (<div>
      <MyComponent/>
    </div>);
  }
}

export default App;

**Comment by fabien0102** [comment]
@jasonrberk Sorry for the very very late response! I totally missed the notification (and we don't have a lot of maintenance on this project)

Very good catch, indeed! 👌 

I will correct the documentation immediatly, the example should be

```tsx
// components/MyComponents.tsx
import react from "React";
import Config from "./Config";

const MyComponent = () => <Config>{({getConfig}) => <h1 style={{ color: getConfig("color") }}>My title</h1>}</Config>;
```

With `({getConfig}) =>` instead of `getConfig =>`
