### ISSUE TITLE
LICENSE file and copyright notice

### ISSUE THREAD

**Issue by g-io** [contiamo/react-runtime-config#26]
Hi and thank you for that nice piece of OpenSource software!

We would like to use it, however company regulations stipulate that we need to follow OS licenses and attribution very strict.
In this case it would need the LICENSE file with the MIT license text including the correct copyright holder.
That might sound trivial, but it's not clear if the copyright is with the author, or the company Contiamo, or any other party.

I assume this small addition could also help other adopters. We'd be happy if that could be added.

**Comment by micha-f** [comment]
Hi @g-io,
thank you for getting in touch! I added the MIT license.
Please note that we ourselves are not actively using this library anymore. Feel free to use it as is - if you require any adjustments however, I would propose to fork it.
