### ISSUE TITLE
I want the whole object

### ISSUE THREAD

**Issue by TejasQ** [contiamo/react-runtime-config#5]
I would like the `getConfig` method to return the entire config map when called without an argument in order to have the whole map available to pass to the Debug viewer in Operational UI.

More info: https://github.com/contiamo/labs-ui/pull/158/files

**Comment by fabien0102** [comment]
The original idea for this usecase was:

```jsx
<AdminConfig>
  {({fields}) => <Debug values={fields.reduce((mem, f) => ({...mem, [f.path]: f.value}), {})}>}
</AdminConfig>
```

But I'm agree that a simple `getConfig()` for this kind of case can also be a nice to have 👍
